services:
  backend:
    build:
      context: back
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - db
    env_file: back/.env
    environment:
      # Override database infos
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=your_password
      - DB_DATABASE=your_database

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database